# Generated by Django 4.0.5 on 2022-06-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='availability',
            field=models.BooleanField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='nanny',
            name='rates',
            field=models.IntegerField(blank=True),
        ),
    ]
