# Generated by Django 4.0.5 on 2022-06-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_nanny_age_alter_nanny_availability_and_more'),
        ('app', '0002_alter_userprofile_user'),
    ]

    operations = [
    ]
