# Generated by Django 4.0.5 on 2022-06-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_nanny_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nanny',
            name='companies',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
