# Generated by Django 4.0.5 on 2022-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='age',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nanny',
            name='availability',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='nanny',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
