# Generated by Django 4.0.5 on 2022-06-23 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_nanny'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='company',
            field=models.ForeignKey(default='Some String', on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
    ]
