# Generated by Django 4.0.5 on 2022-06-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nanny_age_nanny_availability_nanny_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='nanny',
            name='about',
            field=models.TextField(default='Some String'),
        ),
        migrations.AddField(
            model_name='nanny',
            name='skills',
            field=models.TextField(default='Some String'),
        ),
    ]
