# Generated by Django 4.0.5 on 2022-06-23 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_nanny_company_nanny_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nanny',
            name='company',
        ),
    ]
